apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: orange-wallet
data:
  SPRING_PROFILES_ACTIVE: "prod"

  TZ: "Asia/Jakarta"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "orange_db"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  # Service URLs - All services use unified port 8080 in K8s
  AUTH_SERVICE_URL: "http://authentication-service:8080"
  USER_SERVICE_URL: "http://user-service:8080"
  WALLET_SERVICE_URL: "http://wallet-service:8080"
  TRANSACTION_SERVICE_URL: "http://transaction-service:8080"
  NOTIFICATION_SERVICE_URL: "http://notification-worker:8080"

  WAHA_BASE_URL: "http://waha:3000"

  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
