apiVersion: v2
name: orange-service
description: Generic Helm chart for Orange Wallet microservices
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - spring-boot
  - microservice
  - orange-wallet

maintainers:
  - name: Orange Wallet Team
    email: team@orange-wallet.com
