spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: http://authentication-service:8080
              predicates:
                - Path=/api/v1/auth/**, /api/v1/pin/**, /api/v1/sessions/**, /oauth2/jwks

            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=/api/v1/user/**, /api/v1/users/**

            - id: wallet-service
              uri: http://wallet-service:8080
              predicates:
                - Path=/api/v1/wallet/**, /api/v1/wallets/**

            - id: transaction-service
              uri: http://transaction-service:8080
              predicates:
                - Path=/api/v1/transfers/**, /api/v1/transactions/**, /api/v1/quick-transfers/**, /api/v1/topup/**

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://authentication-service:8080/oauth2/jwks

orange:
  cors:
    allowed-origins:
      - "https://app.orangebybni.my.id"
      - "https://orangebybni.my.id"
      - "https://api.orangebybni.my.id"
      - "https://api-dev.orangebybni.my.id"

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR