apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: external
      port: {{ .Values.service.ports.external }}
      targetPort: {{ .Values.service.ports.external }}
      protocol: TCP
    - name: internal
      port: {{ .Values.service.ports.internal }}
      targetPort: {{ .Values.service.ports.internal }}
      protocol: TCP
    - name: controller
      port: {{ .Values.service.ports.controller }}
      targetPort: {{ .Values.service.ports.controller }}
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
