{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  database: {{ .Values.auth.database | quote }}
{{- end }}
