spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: orange.wallet.bni@gmail.com
    password: sieonmdpjasazdgc
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
orange:
  user-service:
    base-url: http://localhost:8081
    timeout: 5s
  waha-client:
    base-url: http://localhost:3000
    api-key: f5010a544c324fc483623e2031b2b92f
    session-name: default
