spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orange_db
    username: mikasa
    password: mikasa
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
orange:
  gcp:
    storage:
      bucket-name: orange-wallet-users-profiles
      project-id: orange-wallet-project
      service-account-email: orange-wallet-storage@orange-wallet-project.iam.gserviceaccount.com
  kafka:
    producer:
      bootstrap-servers: localhost:9092
