spring:
  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    open-in-view: false

  flyway:
    enabled: true
    create-schemas: true
    schemas: wallet_oltp, wallet_read, infra
    default-schema: wallet_oltp
    locations: classpath:db/migration
    baseline-on-migrate: true
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}

  security:
    invite:
      secret: ${INVITE_SECRET:9evyY2Iopik4onDHa+ygvSoI97DJnUx+2JEOeO9ROUE=}

  kafka:
    admin:
      auto-create: ${SPRING_KAFKA_ADMIN_AUTO_CREATE:true}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        request.timeout.ms: 30000
        delivery.timeout.ms: 120000
        compression.type: snappy
      batch-size: 32768
      linger-ms: 20
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: wallet-read-updater
      auto-offset-reset: earliest
    listener:
      ack-mode: batch
      concurrency: 2

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_MAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
wallet:
  events:
    enabled: ${WALLET_EVENTS_ENABLED:true}
app:
  invite:
    ttl-seconds: 600
    base-url: https://app.orangebybni.com/invites/claim
  mail:
    from: ${SMTP_MAIL:orange.wallet.bni@gmail.com}
    delete-wallet-confirm-base-url: ${APP_DELETE_WALLET_CONFIRM_URL:https://app.orangebybni.my.id/wallet/delete-confirm}
orange:
  limits:
    default:
      perTxMinRp: 1000
      perTxMaxRp: 2000000
      dailyMaxRp: 5000000
      weeklyMaxRp: 20000000
      monthlyMaxRp: 50000000
      enforcePerTx: true
      enforceDaily: true
      enforceWeekly: true
      enforceMonthly: true
      timezone: "Asia/Jakarta"
  kafka:
    topics:
      wallet-created: wallet.events.created
      wallet-updated: wallet.events.updated
      wallet-member-invited: wallet.events.member-invited
      wallet-invite-generated: wallet.events.invite-generated
      wallet-invite-accepted: wallet.events.invite-accepted


logging:
  level:
    root: INFO
    com.bni.orange.wallet: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR
