apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orange-service.fullname" . }}-config
  labels:
    {{- include "orange-service.labels" . | nindent 4 }}
data:
  application.properties: |
    # Spring Boot Configuration
    server.port={{ .Values.service.targetPort }}
    spring.profiles.active={{ .Values.env.SPRING_PROFILES_ACTIVE }}

    # Actuator
    management.endpoints.web.exposure.include=health,info,prometheus
    management.endpoint.health.probes.enabled=true
    management.health.livenessState.enabled=true
    management.health.readinessState.enabled=true
