---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: orange-wallet
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "YOUR_ACCOUNT_TAG",
      "TunnelSecret": "YOUR_TUNNEL_SECRET",
      "TunnelID": "YOUR_TUNNEL_ID"
    }
