apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

resources:
  - cloudflared-secret.yaml
  - cloudflared-config.yaml
  - cloudflared-daemonset.yaml
  - cloudflared-service.yaml

commonLabels:
  app.kubernetes.io/name: cloudflared
  app.kubernetes.io/component: tunnel
  app.kubernetes.io/managed-by: kustomize